version: '3.8'

services:
  backend:
    build:
      context: ./battleship-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - battleship-network

  frontend:
    build:
      context: ./battleship-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - battleship-network

networks:
  battleship-network:
    driver: bridge
