import '../../globals.css' // Ensure this file includes your global styles and Material UI-inspired CSS
import { Inter } from 'next/font/google' // Example font import
import { WebSocketProvider } from './socketContext'
import { GameProvider } from './gameContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} bg-gray-50 text-gray-900 min-h-screen flex flex-col`}
      >
        {/* Header */}
        <header className='bg-white shadow-md border-b border-gray-200 p-4'>
          <div className='container mx-auto flex justify-between items-center'>
            <h1 className='text-2xl font-bold'>Battleshipz</h1>
            <nav>
              <ul className='flex space-x-6'>
                <li>
                  <a href='/' className='text-blue-600 hover:text-blue-800'>
                    Home
                  </a>
                </li>
                <li>
                  <a href='/play' className='text-blue-600 hover:text-blue-800'>
                    Play
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </header>

        {/* Main Content */}
        <main className='flex-1 container mx-auto p-6'>
          <WebSocketProvider>
            <GameProvider>{children} </GameProvider>
          </WebSocketProvider>
        </main>

        {/* Footer */}
        <footer className='bg-white shadow-md border-t border-gray-200 p-4'>
          <div className='container mx-auto text-center text-sm text-gray-600'>
            <p>&copy; 2024 Battleshipz. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  )
}
